FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ARG VITE_STORE_HASH
ARG VITE_CHANNEL_ID=1
ARG VITE_LOCAL_APP_CLIENT_ID
ARG VITE_IS_LOCAL_ENVIRONMENT=FALSE
ARG VITE_ASSETS_ABSOLUTE_PATH
ARG VITE_DISABLE_BUILD_HASH
ARG VITE_STORE_URL
ARG VITE_PORTAL_URL

ENV VITE_STORE_HASH=$VITE_STORE_HASH
ENV VITE_CHANNEL_ID=$VITE_CHANNEL_ID
ENV VITE_LOCAL_APP_CLIENT_ID=$VITE_LOCAL_APP_CLIENT_ID
ENV VITE_IS_LOCAL_ENVIRONMENT=$VITE_IS_LOCAL_ENVIRONMENT
ENV VITE_ASSETS_ABSOLUTE_PATH=$VITE_ASSETS_ABSOLUTE_PATH
ENV VITE_DISABLE_BUILD_HASH=$VITE_DISABLE_BUILD_HASH
ENV VITE_STORE_URL=$VITE_STORE_URL
ENV VITE_PORTAL_URL=$VITE_PORTAL_URL

RUN npm run build

FROM node:20-alpine AS production

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --omit=dev && npm cache clean --force

COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
ENV PORT=5000

EXPOSE 5000

CMD ["npm", "start"]
